Convert classes to dataclass (#148)
* Convert unit class to dataclass (#147)

* Start converting Unit class to use dataclass

* Finish converting Unit class to dataclass

* Run "python -m pytest" instead of "pytest" to add root folder to path

* Attempt to fix CI tests

* Attempt to fix testbots

* Fix tests

* Fix upgradestest bot

* Fix upgradestest bot again

* Fix damage-test bot and queries-test bot

* Update tests

* Remove commented out code

* Add benchmark_bot_ai_init to ci

* Fix queries_test_bot

* Rewrite post init as properties

* Add _prepare_units benchmark

* Add docstring, remove post_init and fix EffectId

* Convert game_data to dataclass (#150)

* Convert game_data to dataclass

* Fix structure_type_build_progress for units without creation ability

* Fix typo

* Refactor game_info and power_source (#151)

* Refactor game_info and power_source

* Improve calculation

* Refactor Ramp to be a dataclass

* Refactor game_info to be a dataclass but keeps using proto data

* Rename from_proto_string to from_proto_dict

* Add test to check protobuf implementation

* Add pre-commit hook to tests

* Fix tests

* Add dict generation to CI

* Supress importerror

* Change hook-stage to push

* Force exit code 0

* Improve bot_ai benchmark

* Upload generated dicts as artifact

* Refactor CI into one file

* Fix ci.yml

* Clean up ci.yml

* Remove running test from pre-commit hook

* Remove pycache before comparing generated dict with previous

* Undo dataclasses for GameInfo, GameState and Unit

* Fix generate dicts file

* Comment out RepeatedScalarContainer

* Cache pre-commit in CI

* Fix missed undos

* Add missing _find_ramps_and_vision_blockers

* Refactor to using if statement

* Fix RallyTarget from_proto

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,6 @@
 # If you change the name, change the link on  the README.md for the badge too
 name: Tests
 
-
 on:
   push:
     paths:
@@ -9,8 +8,11 @@ on:
     - examples/**
     - test/**
     - docs_generate/**
-    - pyproject.toml
+    - .pre-commit-config.yaml
+    - generate_dicts_from_data_json.py
+    - generate_id_constants_from_stableid.py
     - poetry.lock
+    - pyproject.toml
     - README.md
     - .github/workflows/ci.yml
   pull_request:
@@ -26,9 +28,105 @@ env:
   LATEST_SC2_VERSION: '4.10'
 
 jobs:
+  run_pre_commit_hook:
+    name: Run pre-commit hook
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Set up Python ${{ env.LATEST_PYTHON_VERSION }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ env.LATEST_PYTHON_VERSION }}
+
+    - name: Install poetry
+      run: pip install poetry
+
+    - name: Make poetry use local .venv folder
+      run: poetry config virtualenvs.in-project true
+
+    - name: Cache pre-commit
+      uses: actions/cache@v3
+      with:
+        path: ~/.cache/pre-commit
+        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('.pre-commit.config.yaml') }}
+
+    - name: Cache .venv
+      uses: actions/cache@v3
+      with:
+        path: .venv
+        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
+
+    - name: Install dependencies
+      run: |
+        poetry install
+        poetry run pre-commit install
+
+    - name: Run pre-commit hooks
+      run: poetry run pre-commit run --all-files --hook-stage push
+
+  generate_dicts_from_data_json:
+    name: Generate dicts from data.json
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Set up Python ${{ env.LATEST_PYTHON_VERSION }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ env.LATEST_PYTHON_VERSION }}
+
+    - name: Install poetry
+      run: pip install poetry
+
+    - name: Make poetry use local .venv folder
+      run: poetry config virtualenvs.in-project true
+
+    - name: Cache pre-commit
+      uses: actions/cache@v3
+      with:
+        path: ~/.cache/pre-commit
+        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('.pre-commit.config.yaml') }}
+
+    - name: Cache .venv
+      uses: actions/cache@v3
+      with:
+        path: .venv
+        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
+
+    - name: Install dependencies
+      run: |
+        poetry install
+        poetry run pre-commit install
+
+    - name: Run generate dicts
+      # Check if newly generated file is the same as existing file
+      # Run pre-commit hook to format files, always return exit code 0 to not end CI run
+      run: |
+        mv sc2/dicts sc2/dicts_old
+        poetry run python generate_dicts_from_data_json.py
+        poetry run pre-commit run --all-files --hook-stage push || true
+        rm -rf sc2/dicts/__pycache__ sc2/dicts_old/__pycache__
+
+    - name: Upload generated dicts folder as artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: Generated_dicts
+        path: sc2/dicts
+
+    - name: Compare generated dict files
+      # Exit code will be 0 if the results of both commands are equal
+      run: |
+        [[ `ls sc2/dicts | md5sum` == `ls sc2/dicts_old | md5sum` ]]
+
   run_pytest_tests:
     # Run pytest tests on pickle files (pre-generated SC2 API observations)
     name: Run pytest
+    needs: [run_pre_commit_hook, generate_dicts_from_data_json]
     runs-on: ${{ matrix.os }}
     timeout-minutes: 15
     strategy:
@@ -49,14 +147,13 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
 
-    - name: Install Poetry
-      run: |
-        pip install poetry
+    - name: Install poetry
+      run: pip install poetry
 
     - name: Make poetry use local .venv folder
       run: poetry config virtualenvs.in-project true
 
-    - name: Set up cache
+    - name: Cache .venv
       if: matrix.os != 'windows-latest'
       uses: actions/cache@v3
       with:
@@ -64,52 +161,37 @@ jobs:
         key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
 
     - name: Install dependencies
-      run: |
-        poetry install
-
-    - name: Run yapf autoformat
-      if: matrix.os != 'windows-latest'
-      run: |
-        poetry run yapf --in-place $(git ls-files '*.py')
-
-    - name: Run pylint on sc2 folder
-      if: matrix.os != 'windows-latest'
-      run: |
-        poetry run pylint $(git ls-files '*.py' | grep -E 'sc2/.*')
-
-    - name: Run pylint on examples folder
-      if: matrix.os != 'windows-latest'
-      run: |
-        poetry run pylint $(git ls-files '*.py' | grep -E 'examples/.*')
+      run: poetry install
 
     - name: Run pytest
-      run: |
-        poetry run pytest test
+      run: poetry run python -m pytest test
 
       # Run benchmarks
     - name: Run benchmark benchmark_array_creation
-      run: |
-        poetry run pytest test/benchmark_array_creation.py
+      run: poetry run python -m pytest test/benchmark_array_creation.py
 
     - name: Run benchmark benchmark_distance_two_points
-      run: |
-        poetry run pytest test/benchmark_distance_two_points.py
+      run: poetry run python -m pytest test/benchmark_distance_two_points.py
 
     - name: Run benchmark benchmark_distances_cdist
-      run: |
-        poetry run pytest test/benchmark_distances_cdist.py
+      run: poetry run python -m pytest test/benchmark_distances_cdist.py
 
     - name: Run benchmark benchmark_distances_points_to_point
-      run: |
-        poetry run pytest test/benchmark_distances_points_to_point.py
+      run: poetry run python -m pytest test/benchmark_distances_points_to_point.py
 
     - name: Run benchmark benchmark_distances_units
-      run: |
-        poetry run pytest test/benchmark_distances_units.py
+      run: poetry run python -m pytest test/benchmark_distances_units.py
+
+    - name: Run benchmark benchmark_bot_ai_prepare_units
+      run: poetry run python -m pytest test/benchmark_prepare_units.py
+
+    - name: Run benchmark benchmark_bot_ai_init
+      run: poetry run python -m pytest test/benchmark_bot_ai_init.py
 
   run_test_bots:
     # Run test bots that download the SC2 linux client and run it
     name: Run testbots linux
+    needs: [run_pytest_tests]
     runs-on: ${{ matrix.os }}
     timeout-minutes: 20
     strategy:
@@ -127,16 +209,13 @@ jobs:
     - uses: actions/checkout@v2
 
     - name: Print directories and files
-      run: |
-        sudo apt-get install tree
-        tree
+      run: sudo apt-get install tree && tree
 
     - name: Load and build docker image
       # Build docker image from Dockerfile using specific python and sc2 version
       env:
         BUILD_ARGS: --build-arg PYTHON_VERSION=${{ matrix.python-version }} --build-arg SC2_VERSION=${{ matrix.sc2-version }}
-      run: |
-        docker build -f test/Dockerfile -t $IMAGE_NAME $BUILD_ARGS .
+      run: docker build -f test/Dockerfile -t $IMAGE_NAME $BUILD_ARGS .
 
     - name: Run autotest_bot.py
       # Run bot and list resulting files (replay file, stable_id.json)
@@ -170,13 +249,9 @@ jobs:
   run_example_bots:
     # Run example bots against computer
     name: Run example bots against computer
-    runs-on: ${{ matrix.os }}
+    needs: [run_pytest_tests]
+    runs-on: ubuntu-latest
     timeout-minutes: 60
-    strategy:
-      # Do not allow this test to cancel. Finish all jobs regardless of error
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
     env:
       IMAGE_NAME: burnysc2/python-sc2-docker:local
 
@@ -185,16 +260,13 @@ jobs:
     - uses: actions/checkout@v2
 
     - name: Print directories and files
-      run: |
-        sudo apt-get install tree
-        tree
+      run: sudo apt-get install tree && tree
 
     - name: Load and build docker image
       # Build docker image from Dockerfile using specific python and sc2 version
       env:
         BUILD_ARGS: --build-arg PYTHON_VERSION=${{ env.LATEST_PYTHON_VERSION }} --build-arg SC2_VERSION=${{ env.LATEST_SC2_VERSION }}
-      run: |
-        docker build -f test/Dockerfile -t $IMAGE_NAME $BUILD_ARGS --build-arg VERSION_NUMBER=${{ env.VERSION_NUMBER }} .
+      run: docker build -f test/Dockerfile -t $IMAGE_NAME $BUILD_ARGS --build-arg VERSION_NUMBER=${{ env.VERSION_NUMBER }} .
 
     - name: Run example bots vs computer
       run: |
@@ -237,11 +309,82 @@ jobs:
 #        docker exec -i my_container bash -c "tree"
 #        docker rm -f my_container
 
-  release_to_github_pages:
-    name: GitHub Pages
+  run_coverage:
+    # Run and upload coverage report using python 3.9
+    # This coverage test does not cover the whole testing range, check /bat_files/rune_code_coverage.bat
+    name: Run coverage
+    needs: [run_test_bots, run_example_bots]
     runs-on: ubuntu-latest
-    timeout-minutes: 3
-    needs: [run_pytest_tests, run_test_bots, run_example_bots]
+    timeout-minutes: 30
+    env:
+      IMAGE_NAME: burnysc2/python-sc2-docker:local
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Load and build docker image
+      # Build docker image from Dockerfile using specific python and sc2 version
+      env:
+        BUILD_ARGS: --build-arg PYTHON_VERSION=${{ env.LATEST_PYTHON_VERSION }} --build-arg SC2_VERSION=${{ env.LATEST_SC2_VERSION }}
+      run: docker build -f test/Dockerfile -t $IMAGE_NAME $BUILD_ARGS --build-arg VERSION_NUMBER=${{ env.VERSION_NUMBER }} .
+
+    - name: Set up container
+      run: |
+        mkdir htmlcov
+        docker run -i -d \
+          --mount type=bind,source=$(pwd)/htmlcov,destination=/root/python-sc2/htmlcov \
+          --name my_container \
+          $IMAGE_NAME
+        echo "Install dev requirements because only non dev requirements exist in the docker image at the moment"
+        docker exec -i my_container bash -c "poetry install"
+
+    - name: Run coverage on tests
+      run: docker exec -i my_container bash -c "poetry run pytest --cov=./"
+
+    - name: Run coverage on autotest_bot.py
+      run: docker exec -i my_container bash -c "poetry run coverage run -a test/travis_test_script.py test/autotest_bot.py"
+
+    - name: Run coverage on upgradestest_bot.py
+      run: docker exec -i my_container bash -c "poetry run coverage run -a test/travis_test_script.py test/upgradestest_bot.py"
+
+    - name: Run coverage on damagetest_bot.py
+      run: docker exec -i my_container bash -c "poetry run coverage run -a test/travis_test_script.py test/damagetest_bot.py"
+
+    - name: Run coverage on queries_test_bot.py
+      run: docker exec -i my_container bash -c "poetry run coverage run -a test/travis_test_script.py test/queries_test_bot.py"
+
+# Bots might run differently long each time and create flucuations in code coverage - better to mock behavior instead
+#    - name: Run coverage on example bots
+#      run: |
+#        docker exec -i my_container bash -c "poetry run coverage run -a test/run_example_bots_vs_computer.py"
+
+    - name: Generate xml coverage file
+      run: |
+        docker exec -i my_container bash -c "poetry run coverage xml"
+        docker cp my_container:/root/python-sc2/coverage.xml $(pwd)/coverage.xml
+
+    - name: Upload coverage to Codecov
+      uses: codecov/codecov-action@v2
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
+        files: coverage.xml
+
+    - name: Generate html coverage files in htmlcov/ folder
+      run: |
+        docker exec -i my_container bash -c "poetry run coverage html"
+        echo "Upload htmlcov folder because it was mounted in container, so it will be available in host machine"
+
+    - name: Upload htmlcov/ folder as artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: Coverage_report
+        path: htmlcov
+
+  run_radon:
+    name: Run radon complexity analysis
+    needs: [run_test_bots, run_example_bots]
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
 
     steps:
     - uses: actions/checkout@v2
@@ -251,14 +394,45 @@ jobs:
       with:
         python-version: ${{ env.LATEST_PYTHON_VERSION }}
 
-    - name: Install Poetry
-      run: |
-        pip install poetry
+    - name: Install poetry
+      run: pip install poetry
 
     - name: Make poetry use local .venv folder
       run: poetry config virtualenvs.in-project true
 
-    - name: Set up cache
+    - name: Cache .venv
+      uses: actions/cache@v3
+      with:
+        path: .venv
+        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
+
+    - name: Install dependencies
+      run: poetry install
+
+    - name: Run poetry radon
+      run: poetry run radon cc sc2/ -a -nb
+
+  release_to_github_pages:
+    name: GitHub Pages
+    needs: [run_test_bots, run_example_bots]
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Set up Python ${{ env.LATEST_PYTHON_VERSION }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ env.LATEST_PYTHON_VERSION }}
+
+    - name: Install poetry
+      run: pip install poetry
+
+    - name: Make poetry use local .venv folder
+      run: poetry config virtualenvs.in-project true
+
+    - name: Cache .venv
       if: matrix.os != 'windows-latest'
       uses: actions/cache@v3
       with:
@@ -266,8 +440,7 @@ jobs:
         key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
 
     - name: Install dependencies
-      run: |
-        poetry install
+      run: poetry install
 
     - name: Build docs from scratch
       run: |
@@ -291,10 +464,10 @@ jobs:
         FOLDER: .   # The folder the action should deploy.
 
   release_to_pypi:
-    name: Pypi
+    name: Pypi package release
+    needs: [release_to_github_pages]
     runs-on: ubuntu-latest
     timeout-minutes: 10
-    needs: [run_pytest_tests, run_test_bots, run_example_bots]
 
     steps:
     - uses: actions/checkout@v2
@@ -304,19 +477,15 @@ jobs:
       with:
         python-version: ${{ env.LATEST_PYTHON_VERSION }}
 
-    - name: Install Poetry
-      run: |
-        pip install poetry
+    - name: Install poetry
+      run: pip install poetry
 
     - name: Build package
         # Builds package to dist/* directory
-      run: |
-        poetry build
+      run: poetry build
 
     - name: Publish
         # Publish package on pypi
       if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
       continue-on-error: true
-      run: |
-        poetry publish --username ${{ secrets.pypi_username }} --password ${{ secrets.pypi_password }}
-
+      run: poetry publish --username ${{ secrets.pypi_username }} --password ${{ secrets.pypi_password }}
